# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_4Qkf2j7SwnjXL3Px0-1IoKspjUM5ovc
"""

text = input("Введите текст: ")
n = len(text)

if n <= 2:
    grade = "чудовищно мало"
elif n <= 5:
    grade = "очень мало"
elif n <= 10:
    grade = "мало"
elif n <= 30:
    grade = "ok"
elif n <= 100:
    grade = "много"
else:
    grade = "чудовищно много"

print(grade)

text = input("Введите текст: ")
n = len(text)

grade = (
    "чудовищно много" if n > 100 else
    "много"           if n > 30  else
    "ok"              if n > 10  else
    "мало"            if n > 5   else
    "очень мало"      if n > 2   else
    "чудовищно мало"
)

print(grade)