# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B1yjfaQA6ESlDye1LzraOkDNbtk_KR_s
"""

text = input()
length = len(text)

if length <= 2:
    print("чудовищно мало")
elif length <= 5:
    print("очень мало")
elif length <= 10:
    print("мало")
elif length <= 30:
    print("ok")
elif length <= 100:
    print("много")
else:
    print("чудовищно много")

text = input()
length = len(text)

if length <= 2:
    print("чудовищно мало")
else:
    if length <= 5:
        print("очень мало")
    else:
        if length <= 10:
            print("мало")
        else:
            if length <= 30:
                print("ok")
            else:
                if length <= 100:
                    print("много")
                else:
                    print("чудовищно много")